//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HocTrucTuyen.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public Question()
        {
            this.Answers = new HashSet<Answer>();
        }
    
        public long ID { get; set; }
        public string Description { get; set; }
        public Nullable<int> Category { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Subject { get; set; }
        public Nullable<long> MutipleChoice_ID { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual ICollection<Answer> Answers { get; set; }
        public virtual MutipleChoice MutipleChoice { get; set; }
    }
}
