//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HocTrucTuyen.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        public Teacher()
        {
            this.Courses = new HashSet<Course>();
        }
    
        public long ID { get; set; }
        public string Name { get; set; }
        public Nullable<long> Review { get; set; }
        public Nullable<long> Student { get; set; }
        public Nullable<long> Total_course { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual ICollection<Course> Courses { get; set; }
    }
}
