//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HocTrucTuyen.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course_Detail
    {
        public long ID { get; set; }
        public string Name { get; set; }
        public string Link { get; set; }
        public string Descriptions { get; set; }
        public Nullable<long> Course_ID { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
    
        public virtual Course Course { get; set; }
    }
}
